# Generated by Django 3.2.6 on 2021-08-27 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date', null=True, verbose_name='created date')),
                ('changed_at', models.DateTimeField(auto_now=True, help_text='updated date', null=True, verbose_name='updated date')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_by', models.ForeignKey(blank=True, editable=False, help_text='Who changed it?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_changed_by', to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created it?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('orders', models.ManyToManyField(related_name='shipping_orders', to='orders.Order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
