# Generated by Django 3.2.6 on 2021-08-17 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20210816_2016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date', null=True, verbose_name='created date')),
                ('changed_at', models.DateTimeField(auto_now=True, help_text='updated date', null=True, verbose_name='updated date')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(default=0)),
                ('paid_out', models.BooleanField(default=False, help_text='Helps to easily distinguish the status pay order.', verbose_name='paid_out')),
                ('sent', models.BooleanField(default=False, help_text='Helps to easily distinguish the status Shipping order.')),
                ('changed_by', models.ForeignKey(blank=True, editable=False, help_text='Who changed it?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_changed_by', to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created it?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
